// GET /api/configuracion/usuarios/get_usuarios.php
// Params requeridos: empresas_id (int)
// Tablas: gkpis_usuarios, gkpis_areas, gkpis_cargos
//
// TODO (futuro Claude): reemplazar con fetch real al backend PHP.
//   Firmas a mantener:
//     getAreas()    → Promise<Area[]>
//     getCargos()   → Promise<Cargo[]>
//     get()         → Promise<Usuario[]>

export type { Area, Cargo, Usuario } from './types'
import type { Area, Cargo, Usuario } from './types'

// ---------------------------------------------------------------------------
// Áreas — las mismas 5 que usa AsignacionView (AREAS_MOCK)
// ---------------------------------------------------------------------------

export const AREAS_SEED: Area[] = [
  { id: 1, nombre: 'Tecnología' },
  { id: 2, nombre: 'Recursos Humanos' },
  { id: 3, nombre: 'Finanzas' },
  { id: 4, nombre: 'Operaciones' },
  { id: 5, nombre: 'Comercial' },
]

// ---------------------------------------------------------------------------
// Cargos — 31 puestos distribuidos por área y nivel jerárquico
// ---------------------------------------------------------------------------

export const CARGOS_SEED: Cargo[] = [
  // Tecnología (areaId: 1)
  { id: 1, nombre: 'CTO', areaId: 1, nivelJerarquico: 'director' },
  { id: 2, nombre: 'Desarrollador Senior', areaId: 1, nivelJerarquico: 'profesional' },
  { id: 3, nombre: 'Desarrollador Junior', areaId: 1, nivelJerarquico: 'profesional' },
  { id: 4, nombre: 'DevOps Engineer', areaId: 1, nivelJerarquico: 'profesional' },
  { id: 5, nombre: 'QA Engineer', areaId: 1, nivelJerarquico: 'profesional' },
  { id: 6, nombre: 'Analista de Datos', areaId: 1, nivelJerarquico: 'profesional' },

  // Recursos Humanos (areaId: 2)
  { id: 7, nombre: 'Gerente de RRHH', areaId: 2, nivelJerarquico: 'gerente' },
  { id: 8, nombre: 'Analista de Selección', areaId: 2, nivelJerarquico: 'profesional' },
  { id: 9, nombre: 'Especialista en Capacitación', areaId: 2, nivelJerarquico: 'profesional' },
  { id: 10, nombre: 'Analista de Compensaciones', areaId: 2, nivelJerarquico: 'profesional' },
  { id: 11, nombre: 'Analista de RRHH', areaId: 2, nivelJerarquico: 'profesional' },
  { id: 12, nombre: 'Coordinador de RRHH', areaId: 2, nivelJerarquico: 'jefatura' },

  // Finanzas (areaId: 3)
  { id: 13, nombre: 'CFO', areaId: 3, nivelJerarquico: 'director' },
  { id: 14, nombre: 'Contador General', areaId: 3, nivelJerarquico: 'jefatura' },
  { id: 15, nombre: 'Analista Financiero', areaId: 3, nivelJerarquico: 'profesional' },
  { id: 16, nombre: 'Analista de Costos', areaId: 3, nivelJerarquico: 'profesional' },
  { id: 17, nombre: 'Tesorero', areaId: 3, nivelJerarquico: 'jefatura' },
  { id: 18, nombre: 'Contador Senior', areaId: 3, nivelJerarquico: 'profesional' },
  { id: 19, nombre: 'Controller', areaId: 3, nivelJerarquico: 'jefatura' },

  // Operaciones (areaId: 4)
  { id: 20, nombre: 'Gerente de Operaciones', areaId: 4, nivelJerarquico: 'gerente' },
  { id: 21, nombre: 'Jefe de Producción', areaId: 4, nivelJerarquico: 'jefatura' },
  { id: 22, nombre: 'Supervisor de Operaciones', areaId: 4, nivelJerarquico: 'jefatura' },
  { id: 23, nombre: 'Analista de Procesos', areaId: 4, nivelJerarquico: 'profesional' },
  { id: 24, nombre: 'Coordinador Logístico', areaId: 4, nivelJerarquico: 'profesional' },
  { id: 25, nombre: 'Jefe de Logística', areaId: 4, nivelJerarquico: 'jefatura' },
  { id: 26, nombre: 'Coordinador de Producción', areaId: 4, nivelJerarquico: 'profesional' },
  { id: 27, nombre: 'Supervisor de Calidad', areaId: 4, nivelJerarquico: 'jefatura' },

  // Comercial (areaId: 5)
  { id: 28, nombre: 'Gerente Comercial', areaId: 5, nivelJerarquico: 'gerente' },
  { id: 29, nombre: 'Ejecutivo de Ventas', areaId: 5, nivelJerarquico: 'profesional' },
  { id: 30, nombre: 'Key Account Manager', areaId: 5, nivelJerarquico: 'profesional' },
  { id: 31, nombre: 'Analista de Marketing', areaId: 5, nivelJerarquico: 'profesional' },
]

// ---------------------------------------------------------------------------
// Usuarios — 50 personas distribuidas en las 5 áreas
// ---------------------------------------------------------------------------

export const USUARIOS_SEED: Usuario[] = [
  // — Tecnología (areaId: 1) — 12 personas ———————————————————————————————
  // rolKpi: director→liderLider, jefatura→lider, profesional→trabajador
  {
    id: 1,
    nombre: 'Felipe',
    apellido: 'Soto',
    rut: '12.938.745-3',
    email: 'felipe.soto@empresa.cl',
    areaId: 1,
    cargoId: 1,
    rolKpi: 'liderLider',
  },
  {
    id: 2,
    nombre: 'Rodrigo',
    apellido: 'González',
    rut: '15.432.876-K',
    email: 'rodrigo.gonzalez@empresa.cl',
    areaId: 1,
    cargoId: 2,
    rolKpi: 'lider',
  },
  {
    id: 3,
    nombre: 'Carlos',
    apellido: 'Muñoz',
    rut: '9.876.234-5',
    email: 'carlos.munoz@empresa.cl',
    areaId: 1,
    cargoId: 2,
    rolKpi: 'trabajador',
  },
  {
    id: 4,
    nombre: 'Diego',
    apellido: 'Castro',
    rut: '18.234.567-2',
    email: 'diego.castro@empresa.cl',
    areaId: 1,
    cargoId: 3,
    rolKpi: 'trabajador',
  },
  {
    id: 5,
    nombre: 'Andrés',
    apellido: 'Fuentes',
    rut: '11.567.890-8',
    email: 'andres.fuentes@empresa.cl',
    areaId: 1,
    cargoId: 3,
    rolKpi: 'trabajador',
  },
  {
    id: 6,
    nombre: 'Nicolás',
    apellido: 'Torres',
    rut: '16.789.012-1',
    email: 'nicolas.torres@empresa.cl',
    areaId: 1,
    cargoId: 4,
    rolKpi: 'trabajador',
  },
  {
    id: 7,
    nombre: 'Pablo',
    apellido: 'Herrera',
    rut: '13.456.789-K',
    email: 'pablo.herrera@empresa.cl',
    areaId: 1,
    cargoId: 4,
    rolKpi: 'trabajador',
  },
  {
    id: 8,
    nombre: 'Valentina',
    apellido: 'Rojas',
    rut: '7.654.321-9',
    email: 'valentina.rojas@empresa.cl',
    areaId: 1,
    cargoId: 6,
    rolKpi: 'trabajador',
  },
  {
    id: 9,
    nombre: 'Daniela',
    apellido: 'Silva',
    rut: '19.012.345-6',
    email: 'daniela.silva@empresa.cl',
    areaId: 1,
    cargoId: 3,
    rolKpi: 'trabajador',
  },
  {
    id: 10,
    nombre: 'Sebastián',
    apellido: 'Pérez',
    rut: '14.890.123-4',
    email: 'sebastian.perez@empresa.cl',
    areaId: 1,
    cargoId: 2,
    rolKpi: 'trabajador',
  },
  {
    id: 11,
    nombre: 'Ignacio',
    apellido: 'Vargas',
    rut: '10.234.567-7',
    email: 'ignacio.vargas@empresa.cl',
    areaId: 1,
    cargoId: 5,
    rolKpi: 'trabajador',
  },
  {
    id: 12,
    nombre: 'Francisca',
    apellido: 'Martínez',
    rut: '17.345.678-3',
    email: 'francisca.martinez@empresa.cl',
    areaId: 1,
    cargoId: 5,
    rolKpi: 'trabajador',
  },

  // — Recursos Humanos (areaId: 2) — 8 personas ——————————————————————————
  {
    id: 13,
    nombre: 'María',
    apellido: 'González',
    rut: '8.901.234-K',
    email: 'maria.gonzalez@empresa.cl',
    areaId: 2,
    cargoId: 7,
    rolKpi: 'liderLider',
  },
  {
    id: 14,
    nombre: 'Carolina',
    apellido: 'Díaz',
    rut: '20.123.456-5',
    email: 'carolina.diaz@empresa.cl',
    areaId: 2,
    cargoId: 8,
    rolKpi: 'trabajador',
  },
  {
    id: 15,
    nombre: 'Sandra',
    apellido: 'Morales',
    rut: '12.456.789-8',
    email: 'sandra.morales@empresa.cl',
    areaId: 2,
    cargoId: 8,
    rolKpi: 'trabajador',
  },
  {
    id: 16,
    nombre: 'Patricia',
    apellido: 'Flores',
    rut: '15.789.012-2',
    email: 'patricia.flores@empresa.cl',
    areaId: 2,
    cargoId: 9,
    rolKpi: 'trabajador',
  },
  {
    id: 17,
    nombre: 'Gloria',
    apellido: 'Contreras',
    rut: '9.234.567-1',
    email: 'gloria.contreras@empresa.cl',
    areaId: 2,
    cargoId: 10,
    rolKpi: 'trabajador',
  },
  {
    id: 18,
    nombre: 'Isabel',
    apellido: 'Sepúlveda',
    rut: '18.567.890-K',
    email: 'isabel.sepulveda@empresa.cl',
    areaId: 2,
    cargoId: 11,
    rolKpi: 'trabajador',
  },
  {
    id: 19,
    nombre: 'Javiera',
    apellido: 'Miranda',
    rut: '11.890.123-7',
    email: 'javiera.miranda@empresa.cl',
    areaId: 2,
    cargoId: 12,
    rolKpi: 'lider',
  },
  {
    id: 20,
    nombre: 'Cristián',
    apellido: 'Guerrero',
    rut: '16.234.567-4',
    email: 'cristian.guerrero@empresa.cl',
    areaId: 2,
    cargoId: 8,
    rolKpi: 'trabajador',
  },

  // — Finanzas (areaId: 3) — 10 personas ————————————————————————————————
  {
    id: 21,
    nombre: 'Eduardo',
    apellido: 'Pizarro',
    rut: '13.678.901-9',
    email: 'eduardo.pizarro@empresa.cl',
    areaId: 3,
    cargoId: 13,
    rolKpi: 'liderLider',
  },
  {
    id: 22,
    nombre: 'Jorge',
    apellido: 'Castro',
    rut: '7.890.234-6',
    email: 'jorge.castro@empresa.cl',
    areaId: 3,
    cargoId: 14,
    rolKpi: 'lider',
  },
  {
    id: 23,
    nombre: 'Laura',
    apellido: 'Soto',
    rut: '19.234.567-3',
    email: 'laura.soto@empresa.cl',
    areaId: 3,
    cargoId: 15,
    rolKpi: 'trabajador',
  },
  {
    id: 24,
    nombre: 'Marcelo',
    apellido: 'Fuentes',
    rut: '14.567.890-K',
    email: 'marcelo.fuentes@empresa.cl',
    areaId: 3,
    cargoId: 16,
    rolKpi: 'trabajador',
  },
  {
    id: 25,
    nombre: 'Teresa',
    apellido: 'Rojas',
    rut: '10.901.234-8',
    email: 'teresa.rojas@empresa.cl',
    areaId: 3,
    cargoId: 17,
    rolKpi: 'lider',
  },
  {
    id: 26,
    nombre: 'Víctor',
    apellido: 'González',
    rut: '17.234.567-5',
    email: 'victor.gonzalez@empresa.cl',
    areaId: 3,
    cargoId: 15,
    rolKpi: 'trabajador',
  },
  {
    id: 27,
    nombre: 'Ana',
    apellido: 'Pérez',
    rut: '8.567.890-2',
    email: 'ana.perez@empresa.cl',
    areaId: 3,
    cargoId: 18,
    rolKpi: 'trabajador',
  },
  {
    id: 28,
    nombre: 'Beatriz',
    apellido: 'Silva',
    rut: '20.890.123-1',
    email: 'beatriz.silva@empresa.cl',
    areaId: 3,
    cargoId: 16,
    rolKpi: 'trabajador',
  },
  {
    id: 29,
    nombre: 'Karla',
    apellido: 'Muñoz',
    rut: '12.123.456-K',
    email: 'karla.munoz@empresa.cl',
    areaId: 3,
    cargoId: 15,
    rolKpi: 'trabajador',
  },
  {
    id: 30,
    nombre: 'Luis',
    apellido: 'Torres',
    rut: '15.456.789-7',
    email: 'luis.torres@empresa.cl',
    areaId: 3,
    cargoId: 19,
    rolKpi: 'lider',
  },

  // — Operaciones (areaId: 4) — 12 personas ——————————————————————————————
  {
    id: 31,
    nombre: 'Gabriel',
    apellido: 'Herrera',
    rut: '9.789.012-4',
    email: 'gabriel.herrera@empresa.cl',
    areaId: 4,
    cargoId: 20,
    rolKpi: 'liderLider',
  },
  {
    id: 32,
    nombre: 'Hernán',
    apellido: 'Vargas',
    rut: '18.012.345-9',
    email: 'hernan.vargas@empresa.cl',
    areaId: 4,
    cargoId: 21,
    rolKpi: 'lider',
  },
  {
    id: 33,
    nombre: 'Javier',
    apellido: 'Contreras',
    rut: '11.345.678-6',
    email: 'javier.contreras@empresa.cl',
    areaId: 4,
    cargoId: 22,
    rolKpi: 'lider',
  },
  {
    id: 34,
    nombre: 'Raquel',
    apellido: 'Martínez',
    rut: '16.678.901-3',
    email: 'raquel.martinez@empresa.cl',
    areaId: 4,
    cargoId: 23,
    rolKpi: 'trabajador',
  },
  {
    id: 35,
    nombre: 'Elena',
    apellido: 'Sepúlveda',
    rut: '13.912.345-K',
    email: 'elena.sepulveda@empresa.cl',
    areaId: 4,
    cargoId: 24,
    rolKpi: 'trabajador',
  },
  {
    id: 36,
    nombre: 'Tomás',
    apellido: 'Díaz',
    rut: '7.345.678-8',
    email: 'tomas.diaz@empresa.cl',
    areaId: 4,
    cargoId: 22,
    rolKpi: 'lider',
  },
  {
    id: 37,
    nombre: 'Ximena',
    apellido: 'Morales',
    rut: '19.678.901-5',
    email: 'ximena.morales@empresa.cl',
    areaId: 4,
    cargoId: 23,
    rolKpi: 'trabajador',
  },
  {
    id: 38,
    nombre: 'Jorge',
    apellido: 'Flores',
    rut: '14.012.345-2',
    email: 'jorge.flores@empresa.cl',
    areaId: 4,
    cargoId: 26,
    rolKpi: 'trabajador',
  },
  {
    id: 39,
    nombre: 'Alejandro',
    apellido: 'Silva',
    rut: '10.345.678-1',
    email: 'alejandro.silva@empresa.cl',
    areaId: 4,
    cargoId: 27,
    rolKpi: 'lider',
  },
  {
    id: 40,
    nombre: 'Natalia',
    apellido: 'Castro',
    rut: '17.678.901-K',
    email: 'natalia.castro@empresa.cl',
    areaId: 4,
    cargoId: 23,
    rolKpi: 'trabajador',
  },
  {
    id: 41,
    nombre: 'Pablo',
    apellido: 'Guerrero',
    rut: '8.012.345-7',
    email: 'pablo.guerrero@empresa.cl',
    areaId: 4,
    cargoId: 25,
    rolKpi: 'lider',
  },
  {
    id: 42,
    nombre: 'Claudia',
    apellido: 'Pizarro',
    rut: '20.345.678-4',
    email: 'claudia.pizarro@empresa.cl',
    areaId: 4,
    cargoId: 24,
    rolKpi: 'trabajador',
  },

  // — Comercial (areaId: 5) — 8 personas ————————————————————————————————
  {
    id: 43,
    nombre: 'Alejandro',
    apellido: 'Muñoz',
    rut: '12.678.901-9',
    email: 'alejandro.munoz@empresa.cl',
    areaId: 5,
    cargoId: 28,
    rolKpi: 'liderLider',
  },
  {
    id: 44,
    nombre: 'Yerlan',
    apellido: 'González',
    rut: '15.012.345-6',
    email: 'yerlan.gonzalez@empresa.cl',
    areaId: 5,
    cargoId: 29,
    rolKpi: 'trabajador',
  },
  {
    id: 45,
    nombre: 'Javiera',
    apellido: 'Torres',
    rut: '9.345.678-3',
    email: 'javiera.torres@empresa.cl',
    areaId: 5,
    cargoId: 30,
    rolKpi: 'lider',
  },
  {
    id: 46,
    nombre: 'José',
    apellido: 'Fuentes',
    rut: '18.678.901-K',
    email: 'jose.fuentes@empresa.cl',
    areaId: 5,
    cargoId: 29,
    rolKpi: 'trabajador',
  },
  {
    id: 47,
    nombre: 'Macarena',
    apellido: 'Rojas',
    rut: '11.012.345-8',
    email: 'macarena.rojas@empresa.cl',
    areaId: 5,
    cargoId: 31,
    rolKpi: 'trabajador',
  },
  {
    id: 48,
    nombre: 'Camilo',
    apellido: 'Pérez',
    rut: '16.345.678-5',
    email: 'camilo.perez@empresa.cl',
    areaId: 5,
    cargoId: 29,
    rolKpi: 'trabajador',
  },
  {
    id: 49,
    nombre: 'Sofía',
    apellido: 'Contreras',
    rut: '13.789.012-2',
    email: 'sofia.contreras@empresa.cl',
    areaId: 5,
    cargoId: 30,
    rolKpi: 'trabajador',
  },
  {
    id: 50,
    nombre: 'Ricardo',
    apellido: 'Vargas',
    rut: '7.123.456-1',
    email: 'ricardo.vargas@empresa.cl',
    areaId: 5,
    cargoId: 29,
    rolKpi: 'trabajador',
  },
]

// ---------------------------------------------------------------------------
// Funciones de acceso — firma idéntica a la que usará el backend PHP real
// ---------------------------------------------------------------------------

export async function getAreas(): Promise<Area[]> {
  return AREAS_SEED
}

export async function getCargos(areaId?: number): Promise<Cargo[]> {
  return areaId !== undefined ? CARGOS_SEED.filter((c) => c.areaId === areaId) : CARGOS_SEED
}

export async function get(areaId?: number): Promise<Usuario[]> {
  return areaId !== undefined ? USUARIOS_SEED.filter((u) => u.areaId === areaId) : USUARIOS_SEED
}
